/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.token.auth.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.AuditedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TokenClient service. Represents a row in the &quot;TokenAuth_TokenClient&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.token.auth.model.impl.TokenClientModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.token.auth.model.impl.TokenClientImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TokenClient
 * @see com.liferay.token.auth.model.impl.TokenClientImpl
 * @see com.liferay.token.auth.model.impl.TokenClientModelImpl
 * @generated
 */
@ProviderType
public interface TokenClientModel extends AuditedModel, BaseModel<TokenClient> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a token client model instance should use the {@link TokenClient} interface instead.
	 */

	/**
	 * Returns the primary key of this token client.
	 *
	 * @return the primary key of this token client
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this token client.
	 *
	 * @param primaryKey the primary key of this token client
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the client ID of this token client.
	 *
	 * @return the client ID of this token client
	 */
	public long getClientId();

	/**
	 * Sets the client ID of this token client.
	 *
	 * @param clientId the client ID of this token client
	 */
	public void setClientId(long clientId);

	/**
	 * Returns the company ID of this token client.
	 *
	 * @return the company ID of this token client
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this token client.
	 *
	 * @param companyId the company ID of this token client
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this token client.
	 *
	 * @return the user ID of this token client
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this token client.
	 *
	 * @param userId the user ID of this token client
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this token client.
	 *
	 * @return the user uuid of this token client
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this token client.
	 *
	 * @param userUuid the user uuid of this token client
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this token client.
	 *
	 * @return the user name of this token client
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this token client.
	 *
	 * @param userName the user name of this token client
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this token client.
	 *
	 * @return the create date of this token client
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this token client.
	 *
	 * @param createDate the create date of this token client
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this token client.
	 *
	 * @return the modified date of this token client
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this token client.
	 *
	 * @param modifiedDate the modified date of this token client
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this token client.
	 *
	 * @return the name of this token client
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this token client.
	 *
	 * @param name the name of this token client
	 */
	public void setName(String name);

	/**
	 * Returns the description of this token client.
	 *
	 * @return the description of this token client
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this token client.
	 *
	 * @param description the description of this token client
	 */
	public void setDescription(String description);

	/**
	 * Returns the client key of this token client.
	 *
	 * @return the client key of this token client
	 */
	@AutoEscape
	public String getClientKey();

	/**
	 * Sets the client key of this token client.
	 *
	 * @param clientKey the client key of this token client
	 */
	public void setClientKey(String clientKey);

	/**
	 * Returns the client secrets of this token client.
	 *
	 * @return the client secrets of this token client
	 */
	@AutoEscape
	public String getClientSecrets();

	/**
	 * Sets the client secrets of this token client.
	 *
	 * @param clientSecrets the client secrets of this token client
	 */
	public void setClientSecrets(String clientSecrets);

	/**
	 * Returns the revoked of this token client.
	 *
	 * @return the revoked of this token client
	 */
	public boolean getRevoked();

	/**
	 * Returns <code>true</code> if this token client is revoked.
	 *
	 * @return <code>true</code> if this token client is revoked; <code>false</code> otherwise
	 */
	public boolean isRevoked();

	/**
	 * Sets whether this token client is revoked.
	 *
	 * @param revoked the revoked of this token client
	 */
	public void setRevoked(boolean revoked);

	/**
	 * Returns the acl profiles of this token client.
	 *
	 * @return the acl profiles of this token client
	 */
	@AutoEscape
	public String getAclProfiles();

	/**
	 * Sets the acl profiles of this token client.
	 *
	 * @param aclProfiles the acl profiles of this token client
	 */
	public void setAclProfiles(String aclProfiles);

	/**
	 * Returns the token verifier ID of this token client.
	 *
	 * @return the token verifier ID of this token client
	 */
	@AutoEscape
	public String getTokenVerifierId();

	/**
	 * Sets the token verifier ID of this token client.
	 *
	 * @param tokenVerifierId the token verifier ID of this token client
	 */
	public void setTokenVerifierId(String tokenVerifierId);

	/**
	 * Returns the callback u r i of this token client.
	 *
	 * @return the callback u r i of this token client
	 */
	@AutoEscape
	public String getCallbackURI();

	/**
	 * Sets the callback u r i of this token client.
	 *
	 * @param callbackURI the callback u r i of this token client
	 */
	public void setCallbackURI(String callbackURI);

	/**
	 * Returns the website u r l of this token client.
	 *
	 * @return the website u r l of this token client
	 */
	@AutoEscape
	public String getWebsiteURL();

	/**
	 * Sets the website u r l of this token client.
	 *
	 * @param websiteURL the website u r l of this token client
	 */
	public void setWebsiteURL(String websiteURL);

	/**
	 * Returns the additional info of this token client.
	 *
	 * @return the additional info of this token client
	 */
	@AutoEscape
	public String getAdditionalInfo();

	/**
	 * Sets the additional info of this token client.
	 *
	 * @param additionalInfo the additional info of this token client
	 */
	public void setAdditionalInfo(String additionalInfo);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.liferay.token.auth.model.TokenClient tokenClient);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.token.auth.model.TokenClient> toCacheModel();

	@Override
	public com.liferay.token.auth.model.TokenClient toEscapedModel();

	@Override
	public com.liferay.token.auth.model.TokenClient toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}