/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.token.auth.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TokenSession service. Represents a row in the &quot;TokenAuth_TokenSession&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.token.auth.model.impl.TokenSessionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.token.auth.model.impl.TokenSessionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TokenSession
 * @see com.liferay.token.auth.model.impl.TokenSessionImpl
 * @see com.liferay.token.auth.model.impl.TokenSessionModelImpl
 * @generated
 */
@ProviderType
public interface TokenSessionModel extends BaseModel<TokenSession> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a token session model instance should use the {@link TokenSession} interface instead.
	 */

	/**
	 * Returns the primary key of this token session.
	 *
	 * @return the primary key of this token session
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this token session.
	 *
	 * @param primaryKey the primary key of this token session
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the session ID of this token session.
	 *
	 * @return the session ID of this token session
	 */
	public long getSessionId();

	/**
	 * Sets the session ID of this token session.
	 *
	 * @param sessionId the session ID of this token session
	 */
	public void setSessionId(long sessionId);

	/**
	 * Returns the company ID of this token session.
	 *
	 * @return the company ID of this token session
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this token session.
	 *
	 * @param companyId the company ID of this token session
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this token session.
	 *
	 * @return the user ID of this token session
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this token session.
	 *
	 * @param userId the user ID of this token session
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this token session.
	 *
	 * @return the user uuid of this token session
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this token session.
	 *
	 * @param userUuid the user uuid of this token session
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this token session.
	 *
	 * @return the user name of this token session
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this token session.
	 *
	 * @param userName the user name of this token session
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this token session.
	 *
	 * @return the create date of this token session
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this token session.
	 *
	 * @param createDate the create date of this token session
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the client ID of this token session.
	 *
	 * @return the client ID of this token session
	 */
	public long getClientId();

	/**
	 * Sets the client ID of this token session.
	 *
	 * @param clientId the client ID of this token session
	 */
	public void setClientId(long clientId);

	/**
	 * Returns the token of this token session.
	 *
	 * @return the token of this token session
	 */
	@AutoEscape
	public String getToken();

	/**
	 * Sets the token of this token session.
	 *
	 * @param token the token of this token session
	 */
	public void setToken(String token);

	/**
	 * Returns the remote info of this token session.
	 *
	 * @return the remote info of this token session
	 */
	@AutoEscape
	public String getRemoteInfo();

	/**
	 * Sets the remote info of this token session.
	 *
	 * @param remoteInfo the remote info of this token session
	 */
	public void setRemoteInfo(String remoteInfo);

	/**
	 * Returns the last used date of this token session.
	 *
	 * @return the last used date of this token session
	 */
	public Date getLastUsedDate();

	/**
	 * Sets the last used date of this token session.
	 *
	 * @param lastUsedDate the last used date of this token session
	 */
	public void setLastUsedDate(Date lastUsedDate);

	/**
	 * Returns the additional info of this token session.
	 *
	 * @return the additional info of this token session
	 */
	@AutoEscape
	public String getAdditionalInfo();

	/**
	 * Sets the additional info of this token session.
	 *
	 * @param additionalInfo the additional info of this token session
	 */
	public void setAdditionalInfo(String additionalInfo);

	/**
	 * Returns the expiry date of this token session.
	 *
	 * @return the expiry date of this token session
	 */
	public Date getExpiryDate();

	/**
	 * Sets the expiry date of this token session.
	 *
	 * @param expiryDate the expiry date of this token session
	 */
	public void setExpiryDate(Date expiryDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.liferay.token.auth.model.TokenSession tokenSession);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.token.auth.model.TokenSession> toCacheModel();

	@Override
	public com.liferay.token.auth.model.TokenSession toEscapedModel();

	@Override
	public com.liferay.token.auth.model.TokenSession toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}