/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.token.auth.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.AuditedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TokenACLProfile service. Represents a row in the &quot;TokenAuth_TokenACLProfile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.token.auth.model.impl.TokenACLProfileModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.token.auth.model.impl.TokenACLProfileImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TokenACLProfile
 * @see com.liferay.token.auth.model.impl.TokenACLProfileImpl
 * @see com.liferay.token.auth.model.impl.TokenACLProfileModelImpl
 * @generated
 */
@ProviderType
public interface TokenACLProfileModel extends AuditedModel,
	BaseModel<TokenACLProfile> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a token a c l profile model instance should use the {@link TokenACLProfile} interface instead.
	 */

	/**
	 * Returns the primary key of this token a c l profile.
	 *
	 * @return the primary key of this token a c l profile
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this token a c l profile.
	 *
	 * @param primaryKey the primary key of this token a c l profile
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the acl profile ID of this token a c l profile.
	 *
	 * @return the acl profile ID of this token a c l profile
	 */
	public long getAclProfileId();

	/**
	 * Sets the acl profile ID of this token a c l profile.
	 *
	 * @param aclProfileId the acl profile ID of this token a c l profile
	 */
	public void setAclProfileId(long aclProfileId);

	/**
	 * Returns the company ID of this token a c l profile.
	 *
	 * @return the company ID of this token a c l profile
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this token a c l profile.
	 *
	 * @param companyId the company ID of this token a c l profile
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this token a c l profile.
	 *
	 * @return the user ID of this token a c l profile
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this token a c l profile.
	 *
	 * @param userId the user ID of this token a c l profile
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this token a c l profile.
	 *
	 * @return the user uuid of this token a c l profile
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this token a c l profile.
	 *
	 * @param userUuid the user uuid of this token a c l profile
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this token a c l profile.
	 *
	 * @return the user name of this token a c l profile
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this token a c l profile.
	 *
	 * @param userName the user name of this token a c l profile
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this token a c l profile.
	 *
	 * @return the create date of this token a c l profile
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this token a c l profile.
	 *
	 * @param createDate the create date of this token a c l profile
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this token a c l profile.
	 *
	 * @return the modified date of this token a c l profile
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this token a c l profile.
	 *
	 * @param modifiedDate the modified date of this token a c l profile
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this token a c l profile.
	 *
	 * @return the name of this token a c l profile
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this token a c l profile.
	 *
	 * @param name the name of this token a c l profile
	 */
	public void setName(String name);

	/**
	 * Returns the description of this token a c l profile.
	 *
	 * @return the description of this token a c l profile
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this token a c l profile.
	 *
	 * @param description the description of this token a c l profile
	 */
	public void setDescription(String description);

	/**
	 * Returns the acl of this token a c l profile.
	 *
	 * @return the acl of this token a c l profile
	 */
	@AutoEscape
	public String getAcl();

	/**
	 * Sets the acl of this token a c l profile.
	 *
	 * @param acl the acl of this token a c l profile
	 */
	public void setAcl(String acl);

	/**
	 * Returns the parent profile ID of this token a c l profile.
	 *
	 * @return the parent profile ID of this token a c l profile
	 */
	public long getParentProfileId();

	/**
	 * Sets the parent profile ID of this token a c l profile.
	 *
	 * @param parentProfileId the parent profile ID of this token a c l profile
	 */
	public void setParentProfileId(long parentProfileId);

	/**
	 * Returns the effective a c l of this token a c l profile.
	 *
	 * @return the effective a c l of this token a c l profile
	 */
	@AutoEscape
	public String getEffectiveACL();

	/**
	 * Sets the effective a c l of this token a c l profile.
	 *
	 * @param effectiveACL the effective a c l of this token a c l profile
	 */
	public void setEffectiveACL(String effectiveACL);

	/**
	 * Returns the system of this token a c l profile.
	 *
	 * @return the system of this token a c l profile
	 */
	public boolean getSystem();

	/**
	 * Returns <code>true</code> if this token a c l profile is system.
	 *
	 * @return <code>true</code> if this token a c l profile is system; <code>false</code> otherwise
	 */
	public boolean isSystem();

	/**
	 * Sets whether this token a c l profile is system.
	 *
	 * @param system the system of this token a c l profile
	 */
	public void setSystem(boolean system);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.liferay.token.auth.model.TokenACLProfile tokenACLProfile);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.token.auth.model.TokenACLProfile> toCacheModel();

	@Override
	public com.liferay.token.auth.model.TokenACLProfile toEscapedModel();

	@Override
	public com.liferay.token.auth.model.TokenACLProfile toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}